[project]
name = "djangoui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asgiref==3.8.1",
    "certifi==2024.8.30",
    "cffi==1.17.1",
    "channels==4.1.0",
    "charset-normalizer==3.4.0",
    "click==8.1.7",
    "colabexts>=0.12300000000000003",
    "contourpy==1.3.0",
    "cryptography==43.0.1",
    "cycler==0.12.1",
    "django==5.1.2",
    "django-allauth==65.0.2",
    "django-extensions==3.2.3",
    "django-oauth-toolkit==3.0.1",
    "django-proxy==1.3.0",
    "et-xmlfile==1.1.0",
    "fonttools==4.54.1",
    "h11==0.14.0",
    "idna==3.10",
    "ipython>=9.4.0",
    "josepy==1.14.0",
    "jwcrypto==1.5.6",
    "kiwisolver==1.4.7",
    "langchain-ollama>=0.3.6",
    "librosa>=0.11.0",
    "mangorest>=0.14700000000000005",
    "matplotlib==3.9.2",
    "mozilla-django-oidc==4.0.1",
    "numpy==2.1.2",
    "oauth2-provider==0.0",
    "oauthlib==3.2.2",
    "ollama>=0.5.1",
    "openai>=1.98.0",
    "openpyxl==3.1.5",
    "packaging==24.1",
    "pandas>=2.3.1",
    "pillow>=11.3.0",
    "pycparser==2.22",
    "pyopenssl==24.2.1",
    "pyparsing==3.2.0",
    "python-dateutil==2.9.0.post0",
    "pytz==2024.2",
    "requests==2.32.3",
    "setuptools==75.2.0",
    "six==1.16.0",
    "sqlparse==0.5.1",
    "torch>=2.7.1",
    "typing-extensions==4.12.2",
    "tzdata==2024.2",
    "urllib3==2.2.3",
    "uvicorn[standard]==0.32.0",
]
