#!/usr/bin/env python

# DO NOT EDIT THIS FILE : Generated from scribe/notebooks/wakeword.ipynb

from mangorest import mango
from  mangorest.mango import webapi
import colabexts.utils as colabexts_utils
import logging
import numpy as np
logger = logging.getLogger( "geoapp" )

# ------------------------------------------------------------------------------
owwModel  = None
wakeword_models=["hey jarvis", "alexa"]
#wakeword_models=[]
def getModel():
    global owwModel, wakeword_models
    import numpy as np
    from openwakeword import Model
    
    if ( owwModel is None):
        if (wakeword_models):
            owwModel = Model(wakeword_models=wakeword_models, inference_framework="onnx")
        else:
            owwModel = Model(inference_framework="onnx")
    return owwModel

@webapi("/geoaudio/detectWakeword/")
def detectWakeword(request=None, audio_bytes=None, **kwargs): 
    if ( request and request.FILES.getlist('file')):
        for f in request.FILES.getlist('file'):
            audio_bytes = f.read()
            break;
    if (not audio_bytes):
        return dict(activations=[])
    
    # Add extra bytes of silence if needed
    if len(audio_bytes) % 2 == 1:
        audio_bytes += (b'\x00')

    # Convert audio to correct format and sample rate
    data = np.frombuffer(audio_bytes, dtype=np.int16)
    #if sample_rate != 16000:
    #    data = resampy.resample(data, sample_rate, 16000)

    # Get openWakeWord predictions and set to browser client
    predictions = getModel().predict(data)
    ret = []
    for key in predictions:
        if predictions[key] >= 0.5:
            ret.append(key)
            
    if ( not ret):
        ret = ""
    
    return ret

if __name__ == '__main__' and not colabexts_utils.inJupyter():
    detectWakeWord(None, None)
