apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ontology-experiment.fullname" . }}-config
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
data:
  OAUTH_CLIENT_ID_DEV: "{{ .Values.app.config.oauth_client_id_dev }}"