kind: Secret
apiVersion: v1
metadata:
  name: {{ include "ontology-experiment.fullname" . }}-secrets
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
type: Opaque
data:
  REPLACE_ME: {{ .Values.app.secrets.replace_me | b64enc }}
